# Specify the base image
FROM node:10.17.0-alpine

# Specify the working dir in docker conatiner
WORKDIR '/app'

# Move the package.json file in the container
COPY ./package.json .
# Install the dependencies
RUN npm install
# Move all the left over files
COPY . .
# Specify the start up command
CMD [ "npm", "run", "start" ]